name: QA (automatic)

on:
  pull_request:
    branches:
      - main
      - dev
      - develop
      - staging

    paths:
      - '**/*'

    # see <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#discussion>
    types:
      - opened
      - reopened
      - unlocked
      - edited
      - assigned
      - review_requested
      - ready_for_review

permissions:
  contents: read

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    environment: "local"
    env: {}

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Action - install justfile tool
        uses: extractions/setup-just@v2
        with:
          just-version: "1.14.0"

      - name: Action - install zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: "0.12.0"

      - name: Setup - ping basic tools and perform pre-installation
        shell: bash
        run: |-
          just --version
          zig version

      - name: STEP 1 - build code
        shell: bash
        run: |-
          just setup
          just build

      - name:  STEP 2 - run linting
        shell: bash
        run: |-
          # NOTE: passively checks if linting _can_ be performed
          # not if it _has_ been performed.
          just lint "src"
          just lint "tests"

      - name:  STEP 3 - run unit tests
        shell: bash
        run: |-
          just tests-unit

      - name:  STEP 4 - run behavioural tests
        shell: bash
        run: |-
          just tests-behave

      - name:  STEP 5 - run as an example
        shell: bash
        run: |-
          just run-exe
          just run-exe "James"
          just run-exe "Julia"
